version: "3.2"
services:
  markdown:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_DOCKER_PORT:$NODE_DOCKER_PORT
    environment:
      - NODE_ENV=$NODE_ENV
      - CHUCK_NORRIS_API=$CHUCK_NORRIS_API
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge